language: android
dist: precise
sudo: required
jdk:
- oraclejdk8
before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache
env:
  global:
    # switch glibc to a memory conserving mode
    - MALLOC_ARENA_MAX=2
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10
install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  - if test ! -e $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; then curl https://dl.google.com/android/repository/tools_r25.2.5-linux.zip > $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; fi
  - unzip -n $HOME/android-sdk-dl/tools_r25.2.5-linux.zip -d $HOME/android-sdk

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;25.0.2'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-25'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;android;m2repository'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;google_play_services'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository'
env:
  - ANDROID_HOME=$HOME/android-sdk
before_install:
  - export TZ=Australia/Canberra
script:
  - ./gradlew clean check connectedCheck
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
before_install:
  - chmod +x scripts/ci-mock-google-services-setup.sh
  - ./scripts/ci-mock-google-services-setup.sh
notifications:
  slack:
    secure: luqJp1itNRPGusUaTE3+KkD52LJLg3wCQN6F2M2Z5QMrZdrWk1l/HRn7M+sm6gIKo9O4k2Wn+h0MZsmfOs0mHOQVwaj4FEP1b8qyLqzVMfcmTceV2eX79dGM6m2kVz6180TlI+5+af/+qxLQAe0OCbtvbyWaxoPvmKpBFJn3Cq02mTFhCU+sT9qfMYwugehXxTdz5o/+jTxTh2dd4Gvs02b/EHKxWfohsj6/aZ4eH6tsJM2O/PV0uv4po+87JvNjHzN6Xjz3LqVuvMFHXgsaJLuU8V0YARdAcOMLhtYJhvUERIsZvnZ1F3t+DNS2S1zIOihC4tol6Nwbvq89fsoAG/2sIGfcoqc49AFqX0Mx1yyizjVL6xSSCAfozHZvQTs3aD7d2tLJst3ABelenQgCO5dzBcOczwCTPNisVOaGuzWpW79dwg1lyV5rq2Ctj8Vby5IHe+0+pm+jUTxZaE5XjLEdw7auuHtzhssLLvaIJEDy17uhYRuUoFYE5AqGIkHzgLMzin5d4Y82k9aXICaMdJQxDbY2Szl9cvy7dVayQ96wgrl681OfVigZtDrrfJeAoA1OhSJQ4C40B2uU6pXBf8uXPuBouyoqRPrB6LKtDbmzQzFFFbp9y26On2rqklNQlHqvqgw77mQGA1m5oAJzsEH7WddsVXiViZKtXrXF6ME=
