site_name: NearIT Android
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - 'Index' : 'index.md'
  - 'User Guide' : 
    - 'Enable Triggers' : 'enable-triggers.md'
    - 'Handle recipe content' : 'handle-content.md'
