site_name: NearIT Android
extra_css: css/nearitdocs.css
pages:
  - 'Index' : 'index.md'
  - 'User Guide' : 
    - 'Enable Triggers' : 'enable-triggers.md'
    - 'Handle recipe content' : 'handle-content.md'
